########################### Navigation ###################################
menu:
  # main menu
  main:
    - { name: Home, url: "/" }
    - { name: Contact, url: "contact.html" }
    #- { name: Tools, url: "tools.html" }

  ##### Dropdown menu ######

  # - name: dropdown
  #   submenu:
  #   - name : "d1"
  #     url : "#"
  #   - name : "d2"
  #     url : "#"

  ##########################

  # Footer menu
  footer:
    - { name: Home, url: "/" }
    - { name: Contact, url: "contact.html" }
   # - { name: Tools, url: "tools.html" }

######################### Default Parameters ###########################

# logo
logo: "" #"/assets/images/logo-no-background.svg"

# meta data
author: "Magnus Larsson"
description: "This is my personal blog where I occasionally write about topics that interest me."

# google analitycs ID
google_analitycs_id: "" # your id
# contact form action
contact_form_action: "https://formspree.io/f/mpzvapvk" # contact form works with : https://formspree.io
# copyright
copyright: ""

# preloader
preloader:
  enable: true
  preloader: "" # use png, jpg, svg or gif format

# search
search:
  enable: true

############################## Social Site ##########################
social:
 # - name: "facebook"
 #   icon: "ti-facebook" # themify icon pack https://themify.me/themify-icons
 #   link: "#"

 # - name: "twitter"
 #   icon: "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
 #   link: "#"

 # - name: "github"
 #   icon: "ti-github" # themify icon pack https://themify.me/themify-icons
 #   link: "#"

  - name: "linkedin"
    icon: "ti-linkedin" # themify icon pack https://themify.me/themify-icons
    link: "https://linkedin.com/in/magnuslarsson76"
